/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ManifestoRouteImport } from './routes/manifesto'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as CustodyRouteImport } from './routes/custody'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TradeZcuTsdRouteImport } from './routes/trade.zcu-tsd'
import { Route as TradeUsdcTxcRouteImport } from './routes/trade.usdc-txc'
import { Route as TradeTxcUsdtRouteImport } from './routes/trade.txc-usdt'
import { Route as TradeTsdUsdcRouteImport } from './routes/trade.tsd-usdc'
import { Route as TradeTsdTxcRouteImport } from './routes/trade.tsd-txc'
import { Route as TradeLtcTsdRouteImport } from './routes/trade.ltc-tsd'
import { Route as TradeIskTsdRouteImport } from './routes/trade.isk-tsd'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as AuthenticatedTradesRouteImport } from './routes/_authenticated/trades'
import { Route as ApiPublicV1IndexRouteImport } from './routes/api/public/v1/index'
import { Route as ApiPublicCmcIndexRouteImport } from './routes/api/public/cmc/index'
import { Route as ApiPublicV1TradesRouteImport } from './routes/api/public/v1/trades'
import { Route as ApiPublicV1TimeRouteImport } from './routes/api/public/v1/time'
import { Route as ApiPublicV1PingRouteImport } from './routes/api/public/v1/ping'
import { Route as ApiPublicV1OpenOrdersRouteImport } from './routes/api/public/v1/openOrders'
import { Route as ApiPublicV1KlinesRouteImport } from './routes/api/public/v1/klines'
import { Route as ApiPublicV1ExchangeInfoRouteImport } from './routes/api/public/v1/exchangeInfo'
import { Route as ApiPublicV1DepthRouteImport } from './routes/api/public/v1/depth'
import { Route as ApiPublicV1AccountRouteImport } from './routes/api/public/v1/account'
import { Route as ApiPublicCmcTickerRouteImport } from './routes/api/public/cmc/ticker'
import { Route as ApiPublicCmcSummaryRouteImport } from './routes/api/public/cmc/summary'
import { Route as ApiPublicCmcAssetsRouteImport } from './routes/api/public/cmc/assets'
import { Route as ApiPublicV1TickerPriceRouteImport } from './routes/api/public/v1/ticker/price'
import { Route as ApiPublicV1Ticker24hrRouteImport } from './routes/api/public/v1/ticker/24hr'
import { Route as ApiPublicCmcTradesPairRouteImport } from './routes/api/public/cmc/trades.$pair'
import { Route as ApiPublicCmcOrderbookPairRouteImport } from './routes/api/public/cmc/orderbook.$pair'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestoRoute = ManifestoRouteImport.update({
  id: '/manifesto',
  path: '/manifesto',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const CustodyRoute = CustodyRouteImport.update({
  id: '/custody',
  path: '/custody',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeZcuTsdRoute = TradeZcuTsdRouteImport.update({
  id: '/trade/zcu-tsd',
  path: '/trade/zcu-tsd',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeUsdcTxcRoute = TradeUsdcTxcRouteImport.update({
  id: '/trade/usdc-txc',
  path: '/trade/usdc-txc',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeTxcUsdtRoute = TradeTxcUsdtRouteImport.update({
  id: '/trade/txc-usdt',
  path: '/trade/txc-usdt',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeTsdUsdcRoute = TradeTsdUsdcRouteImport.update({
  id: '/trade/tsd-usdc',
  path: '/trade/tsd-usdc',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeTsdTxcRoute = TradeTsdTxcRouteImport.update({
  id: '/trade/tsd-txc',
  path: '/trade/tsd-txc',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeLtcTsdRoute = TradeLtcTsdRouteImport.update({
  id: '/trade/ltc-tsd',
  path: '/trade/ltc-tsd',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeIskTsdRoute = TradeIskTsdRouteImport.update({
  id: '/trade/isk-tsd',
  path: '/trade/isk-tsd',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTradesRoute = AuthenticatedTradesRouteImport.update({
  id: '/trades',
  path: '/trades',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicV1IndexRoute = ApiPublicV1IndexRouteImport.update({
  id: '/api/public/v1/',
  path: '/api/public/v1/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCmcIndexRoute = ApiPublicCmcIndexRouteImport.update({
  id: '/api/public/cmc/',
  path: '/api/public/cmc/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1TradesRoute = ApiPublicV1TradesRouteImport.update({
  id: '/api/public/v1/trades',
  path: '/api/public/v1/trades',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1TimeRoute = ApiPublicV1TimeRouteImport.update({
  id: '/api/public/v1/time',
  path: '/api/public/v1/time',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1PingRoute = ApiPublicV1PingRouteImport.update({
  id: '/api/public/v1/ping',
  path: '/api/public/v1/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1OpenOrdersRoute = ApiPublicV1OpenOrdersRouteImport.update({
  id: '/api/public/v1/openOrders',
  path: '/api/public/v1/openOrders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1KlinesRoute = ApiPublicV1KlinesRouteImport.update({
  id: '/api/public/v1/klines',
  path: '/api/public/v1/klines',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1ExchangeInfoRoute = ApiPublicV1ExchangeInfoRouteImport.update({
  id: '/api/public/v1/exchangeInfo',
  path: '/api/public/v1/exchangeInfo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1DepthRoute = ApiPublicV1DepthRouteImport.update({
  id: '/api/public/v1/depth',
  path: '/api/public/v1/depth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1AccountRoute = ApiPublicV1AccountRouteImport.update({
  id: '/api/public/v1/account',
  path: '/api/public/v1/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCmcTickerRoute = ApiPublicCmcTickerRouteImport.update({
  id: '/api/public/cmc/ticker',
  path: '/api/public/cmc/ticker',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCmcSummaryRoute = ApiPublicCmcSummaryRouteImport.update({
  id: '/api/public/cmc/summary',
  path: '/api/public/cmc/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCmcAssetsRoute = ApiPublicCmcAssetsRouteImport.update({
  id: '/api/public/cmc/assets',
  path: '/api/public/cmc/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1TickerPriceRoute = ApiPublicV1TickerPriceRouteImport.update({
  id: '/api/public/v1/ticker/price',
  path: '/api/public/v1/ticker/price',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1Ticker24hrRoute = ApiPublicV1Ticker24hrRouteImport.update({
  id: '/api/public/v1/ticker/24hr',
  path: '/api/public/v1/ticker/24hr',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCmcTradesPairRoute = ApiPublicCmcTradesPairRouteImport.update({
  id: '/api/public/cmc/trades/$pair',
  path: '/api/public/cmc/trades/$pair',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCmcOrderbookPairRoute =
  ApiPublicCmcOrderbookPairRouteImport.update({
    id: '/api/public/cmc/orderbook/$pair',
    path: '/api/public/cmc/orderbook/$pair',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/custody': typeof CustodyRoute
  '/how-it-works': typeof HowItWorksRoute
  '/manifesto': typeof ManifestoRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/trades': typeof AuthenticatedTradesRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/trade/isk-tsd': typeof TradeIskTsdRoute
  '/trade/ltc-tsd': typeof TradeLtcTsdRoute
  '/trade/tsd-txc': typeof TradeTsdTxcRoute
  '/trade/tsd-usdc': typeof TradeTsdUsdcRoute
  '/trade/txc-usdt': typeof TradeTxcUsdtRoute
  '/trade/usdc-txc': typeof TradeUsdcTxcRoute
  '/trade/zcu-tsd': typeof TradeZcuTsdRoute
  '/api/public/cmc/assets': typeof ApiPublicCmcAssetsRoute
  '/api/public/cmc/summary': typeof ApiPublicCmcSummaryRoute
  '/api/public/cmc/ticker': typeof ApiPublicCmcTickerRoute
  '/api/public/v1/account': typeof ApiPublicV1AccountRoute
  '/api/public/v1/depth': typeof ApiPublicV1DepthRoute
  '/api/public/v1/exchangeInfo': typeof ApiPublicV1ExchangeInfoRoute
  '/api/public/v1/klines': typeof ApiPublicV1KlinesRoute
  '/api/public/v1/openOrders': typeof ApiPublicV1OpenOrdersRoute
  '/api/public/v1/ping': typeof ApiPublicV1PingRoute
  '/api/public/v1/time': typeof ApiPublicV1TimeRoute
  '/api/public/v1/trades': typeof ApiPublicV1TradesRoute
  '/api/public/cmc/': typeof ApiPublicCmcIndexRoute
  '/api/public/v1/': typeof ApiPublicV1IndexRoute
  '/api/public/cmc/orderbook/$pair': typeof ApiPublicCmcOrderbookPairRoute
  '/api/public/cmc/trades/$pair': typeof ApiPublicCmcTradesPairRoute
  '/api/public/v1/ticker/24hr': typeof ApiPublicV1Ticker24hrRoute
  '/api/public/v1/ticker/price': typeof ApiPublicV1TickerPriceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/custody': typeof CustodyRoute
  '/how-it-works': typeof HowItWorksRoute
  '/manifesto': typeof ManifestoRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/trades': typeof AuthenticatedTradesRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/trade/isk-tsd': typeof TradeIskTsdRoute
  '/trade/ltc-tsd': typeof TradeLtcTsdRoute
  '/trade/tsd-txc': typeof TradeTsdTxcRoute
  '/trade/tsd-usdc': typeof TradeTsdUsdcRoute
  '/trade/txc-usdt': typeof TradeTxcUsdtRoute
  '/trade/usdc-txc': typeof TradeUsdcTxcRoute
  '/trade/zcu-tsd': typeof TradeZcuTsdRoute
  '/api/public/cmc/assets': typeof ApiPublicCmcAssetsRoute
  '/api/public/cmc/summary': typeof ApiPublicCmcSummaryRoute
  '/api/public/cmc/ticker': typeof ApiPublicCmcTickerRoute
  '/api/public/v1/account': typeof ApiPublicV1AccountRoute
  '/api/public/v1/depth': typeof ApiPublicV1DepthRoute
  '/api/public/v1/exchangeInfo': typeof ApiPublicV1ExchangeInfoRoute
  '/api/public/v1/klines': typeof ApiPublicV1KlinesRoute
  '/api/public/v1/openOrders': typeof ApiPublicV1OpenOrdersRoute
  '/api/public/v1/ping': typeof ApiPublicV1PingRoute
  '/api/public/v1/time': typeof ApiPublicV1TimeRoute
  '/api/public/v1/trades': typeof ApiPublicV1TradesRoute
  '/api/public/cmc': typeof ApiPublicCmcIndexRoute
  '/api/public/v1': typeof ApiPublicV1IndexRoute
  '/api/public/cmc/orderbook/$pair': typeof ApiPublicCmcOrderbookPairRoute
  '/api/public/cmc/trades/$pair': typeof ApiPublicCmcTradesPairRoute
  '/api/public/v1/ticker/24hr': typeof ApiPublicV1Ticker24hrRoute
  '/api/public/v1/ticker/price': typeof ApiPublicV1TickerPriceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/custody': typeof CustodyRoute
  '/how-it-works': typeof HowItWorksRoute
  '/manifesto': typeof ManifestoRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_authenticated/trades': typeof AuthenticatedTradesRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
  '/trade/isk-tsd': typeof TradeIskTsdRoute
  '/trade/ltc-tsd': typeof TradeLtcTsdRoute
  '/trade/tsd-txc': typeof TradeTsdTxcRoute
  '/trade/tsd-usdc': typeof TradeTsdUsdcRoute
  '/trade/txc-usdt': typeof TradeTxcUsdtRoute
  '/trade/usdc-txc': typeof TradeUsdcTxcRoute
  '/trade/zcu-tsd': typeof TradeZcuTsdRoute
  '/api/public/cmc/assets': typeof ApiPublicCmcAssetsRoute
  '/api/public/cmc/summary': typeof ApiPublicCmcSummaryRoute
  '/api/public/cmc/ticker': typeof ApiPublicCmcTickerRoute
  '/api/public/v1/account': typeof ApiPublicV1AccountRoute
  '/api/public/v1/depth': typeof ApiPublicV1DepthRoute
  '/api/public/v1/exchangeInfo': typeof ApiPublicV1ExchangeInfoRoute
  '/api/public/v1/klines': typeof ApiPublicV1KlinesRoute
  '/api/public/v1/openOrders': typeof ApiPublicV1OpenOrdersRoute
  '/api/public/v1/ping': typeof ApiPublicV1PingRoute
  '/api/public/v1/time': typeof ApiPublicV1TimeRoute
  '/api/public/v1/trades': typeof ApiPublicV1TradesRoute
  '/api/public/cmc/': typeof ApiPublicCmcIndexRoute
  '/api/public/v1/': typeof ApiPublicV1IndexRoute
  '/api/public/cmc/orderbook/$pair': typeof ApiPublicCmcOrderbookPairRoute
  '/api/public/cmc/trades/$pair': typeof ApiPublicCmcTradesPairRoute
  '/api/public/v1/ticker/24hr': typeof ApiPublicV1Ticker24hrRoute
  '/api/public/v1/ticker/price': typeof ApiPublicV1TickerPriceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/custody'
    | '/how-it-works'
    | '/manifesto'
    | '/privacy'
    | '/terms'
    | '/trades'
    | '/wallet'
    | '/trade/isk-tsd'
    | '/trade/ltc-tsd'
    | '/trade/tsd-txc'
    | '/trade/tsd-usdc'
    | '/trade/txc-usdt'
    | '/trade/usdc-txc'
    | '/trade/zcu-tsd'
    | '/api/public/cmc/assets'
    | '/api/public/cmc/summary'
    | '/api/public/cmc/ticker'
    | '/api/public/v1/account'
    | '/api/public/v1/depth'
    | '/api/public/v1/exchangeInfo'
    | '/api/public/v1/klines'
    | '/api/public/v1/openOrders'
    | '/api/public/v1/ping'
    | '/api/public/v1/time'
    | '/api/public/v1/trades'
    | '/api/public/cmc/'
    | '/api/public/v1/'
    | '/api/public/cmc/orderbook/$pair'
    | '/api/public/cmc/trades/$pair'
    | '/api/public/v1/ticker/24hr'
    | '/api/public/v1/ticker/price'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/custody'
    | '/how-it-works'
    | '/manifesto'
    | '/privacy'
    | '/terms'
    | '/trades'
    | '/wallet'
    | '/trade/isk-tsd'
    | '/trade/ltc-tsd'
    | '/trade/tsd-txc'
    | '/trade/tsd-usdc'
    | '/trade/txc-usdt'
    | '/trade/usdc-txc'
    | '/trade/zcu-tsd'
    | '/api/public/cmc/assets'
    | '/api/public/cmc/summary'
    | '/api/public/cmc/ticker'
    | '/api/public/v1/account'
    | '/api/public/v1/depth'
    | '/api/public/v1/exchangeInfo'
    | '/api/public/v1/klines'
    | '/api/public/v1/openOrders'
    | '/api/public/v1/ping'
    | '/api/public/v1/time'
    | '/api/public/v1/trades'
    | '/api/public/cmc'
    | '/api/public/v1'
    | '/api/public/cmc/orderbook/$pair'
    | '/api/public/cmc/trades/$pair'
    | '/api/public/v1/ticker/24hr'
    | '/api/public/v1/ticker/price'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/custody'
    | '/how-it-works'
    | '/manifesto'
    | '/privacy'
    | '/terms'
    | '/_authenticated/trades'
    | '/_authenticated/wallet'
    | '/trade/isk-tsd'
    | '/trade/ltc-tsd'
    | '/trade/tsd-txc'
    | '/trade/tsd-usdc'
    | '/trade/txc-usdt'
    | '/trade/usdc-txc'
    | '/trade/zcu-tsd'
    | '/api/public/cmc/assets'
    | '/api/public/cmc/summary'
    | '/api/public/cmc/ticker'
    | '/api/public/v1/account'
    | '/api/public/v1/depth'
    | '/api/public/v1/exchangeInfo'
    | '/api/public/v1/klines'
    | '/api/public/v1/openOrders'
    | '/api/public/v1/ping'
    | '/api/public/v1/time'
    | '/api/public/v1/trades'
    | '/api/public/cmc/'
    | '/api/public/v1/'
    | '/api/public/cmc/orderbook/$pair'
    | '/api/public/cmc/trades/$pair'
    | '/api/public/v1/ticker/24hr'
    | '/api/public/v1/ticker/price'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CustodyRoute: typeof CustodyRoute
  HowItWorksRoute: typeof HowItWorksRoute
  ManifestoRoute: typeof ManifestoRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  TradeIskTsdRoute: typeof TradeIskTsdRoute
  TradeLtcTsdRoute: typeof TradeLtcTsdRoute
  TradeTsdTxcRoute: typeof TradeTsdTxcRoute
  TradeTsdUsdcRoute: typeof TradeTsdUsdcRoute
  TradeTxcUsdtRoute: typeof TradeTxcUsdtRoute
  TradeUsdcTxcRoute: typeof TradeUsdcTxcRoute
  TradeZcuTsdRoute: typeof TradeZcuTsdRoute
  ApiPublicCmcAssetsRoute: typeof ApiPublicCmcAssetsRoute
  ApiPublicCmcSummaryRoute: typeof ApiPublicCmcSummaryRoute
  ApiPublicCmcTickerRoute: typeof ApiPublicCmcTickerRoute
  ApiPublicV1AccountRoute: typeof ApiPublicV1AccountRoute
  ApiPublicV1DepthRoute: typeof ApiPublicV1DepthRoute
  ApiPublicV1ExchangeInfoRoute: typeof ApiPublicV1ExchangeInfoRoute
  ApiPublicV1KlinesRoute: typeof ApiPublicV1KlinesRoute
  ApiPublicV1OpenOrdersRoute: typeof ApiPublicV1OpenOrdersRoute
  ApiPublicV1PingRoute: typeof ApiPublicV1PingRoute
  ApiPublicV1TimeRoute: typeof ApiPublicV1TimeRoute
  ApiPublicV1TradesRoute: typeof ApiPublicV1TradesRoute
  ApiPublicCmcIndexRoute: typeof ApiPublicCmcIndexRoute
  ApiPublicV1IndexRoute: typeof ApiPublicV1IndexRoute
  ApiPublicCmcOrderbookPairRoute: typeof ApiPublicCmcOrderbookPairRoute
  ApiPublicCmcTradesPairRoute: typeof ApiPublicCmcTradesPairRoute
  ApiPublicV1Ticker24hrRoute: typeof ApiPublicV1Ticker24hrRoute
  ApiPublicV1TickerPriceRoute: typeof ApiPublicV1TickerPriceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifesto': {
      id: '/manifesto'
      path: '/manifesto'
      fullPath: '/manifesto'
      preLoaderRoute: typeof ManifestoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custody': {
      id: '/custody'
      path: '/custody'
      fullPath: '/custody'
      preLoaderRoute: typeof CustodyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade/zcu-tsd': {
      id: '/trade/zcu-tsd'
      path: '/trade/zcu-tsd'
      fullPath: '/trade/zcu-tsd'
      preLoaderRoute: typeof TradeZcuTsdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade/usdc-txc': {
      id: '/trade/usdc-txc'
      path: '/trade/usdc-txc'
      fullPath: '/trade/usdc-txc'
      preLoaderRoute: typeof TradeUsdcTxcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade/txc-usdt': {
      id: '/trade/txc-usdt'
      path: '/trade/txc-usdt'
      fullPath: '/trade/txc-usdt'
      preLoaderRoute: typeof TradeTxcUsdtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade/tsd-usdc': {
      id: '/trade/tsd-usdc'
      path: '/trade/tsd-usdc'
      fullPath: '/trade/tsd-usdc'
      preLoaderRoute: typeof TradeTsdUsdcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade/tsd-txc': {
      id: '/trade/tsd-txc'
      path: '/trade/tsd-txc'
      fullPath: '/trade/tsd-txc'
      preLoaderRoute: typeof TradeTsdTxcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade/ltc-tsd': {
      id: '/trade/ltc-tsd'
      path: '/trade/ltc-tsd'
      fullPath: '/trade/ltc-tsd'
      preLoaderRoute: typeof TradeLtcTsdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade/isk-tsd': {
      id: '/trade/isk-tsd'
      path: '/trade/isk-tsd'
      fullPath: '/trade/isk-tsd'
      preLoaderRoute: typeof TradeIskTsdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trades': {
      id: '/_authenticated/trades'
      path: '/trades'
      fullPath: '/trades'
      preLoaderRoute: typeof AuthenticatedTradesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/v1/': {
      id: '/api/public/v1/'
      path: '/api/public/v1'
      fullPath: '/api/public/v1/'
      preLoaderRoute: typeof ApiPublicV1IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cmc/': {
      id: '/api/public/cmc/'
      path: '/api/public/cmc'
      fullPath: '/api/public/cmc/'
      preLoaderRoute: typeof ApiPublicCmcIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/trades': {
      id: '/api/public/v1/trades'
      path: '/api/public/v1/trades'
      fullPath: '/api/public/v1/trades'
      preLoaderRoute: typeof ApiPublicV1TradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/time': {
      id: '/api/public/v1/time'
      path: '/api/public/v1/time'
      fullPath: '/api/public/v1/time'
      preLoaderRoute: typeof ApiPublicV1TimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/ping': {
      id: '/api/public/v1/ping'
      path: '/api/public/v1/ping'
      fullPath: '/api/public/v1/ping'
      preLoaderRoute: typeof ApiPublicV1PingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/openOrders': {
      id: '/api/public/v1/openOrders'
      path: '/api/public/v1/openOrders'
      fullPath: '/api/public/v1/openOrders'
      preLoaderRoute: typeof ApiPublicV1OpenOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/klines': {
      id: '/api/public/v1/klines'
      path: '/api/public/v1/klines'
      fullPath: '/api/public/v1/klines'
      preLoaderRoute: typeof ApiPublicV1KlinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/exchangeInfo': {
      id: '/api/public/v1/exchangeInfo'
      path: '/api/public/v1/exchangeInfo'
      fullPath: '/api/public/v1/exchangeInfo'
      preLoaderRoute: typeof ApiPublicV1ExchangeInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/depth': {
      id: '/api/public/v1/depth'
      path: '/api/public/v1/depth'
      fullPath: '/api/public/v1/depth'
      preLoaderRoute: typeof ApiPublicV1DepthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/account': {
      id: '/api/public/v1/account'
      path: '/api/public/v1/account'
      fullPath: '/api/public/v1/account'
      preLoaderRoute: typeof ApiPublicV1AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cmc/ticker': {
      id: '/api/public/cmc/ticker'
      path: '/api/public/cmc/ticker'
      fullPath: '/api/public/cmc/ticker'
      preLoaderRoute: typeof ApiPublicCmcTickerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cmc/summary': {
      id: '/api/public/cmc/summary'
      path: '/api/public/cmc/summary'
      fullPath: '/api/public/cmc/summary'
      preLoaderRoute: typeof ApiPublicCmcSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cmc/assets': {
      id: '/api/public/cmc/assets'
      path: '/api/public/cmc/assets'
      fullPath: '/api/public/cmc/assets'
      preLoaderRoute: typeof ApiPublicCmcAssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/ticker/price': {
      id: '/api/public/v1/ticker/price'
      path: '/api/public/v1/ticker/price'
      fullPath: '/api/public/v1/ticker/price'
      preLoaderRoute: typeof ApiPublicV1TickerPriceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/ticker/24hr': {
      id: '/api/public/v1/ticker/24hr'
      path: '/api/public/v1/ticker/24hr'
      fullPath: '/api/public/v1/ticker/24hr'
      preLoaderRoute: typeof ApiPublicV1Ticker24hrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cmc/trades/$pair': {
      id: '/api/public/cmc/trades/$pair'
      path: '/api/public/cmc/trades/$pair'
      fullPath: '/api/public/cmc/trades/$pair'
      preLoaderRoute: typeof ApiPublicCmcTradesPairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cmc/orderbook/$pair': {
      id: '/api/public/cmc/orderbook/$pair'
      path: '/api/public/cmc/orderbook/$pair'
      fullPath: '/api/public/cmc/orderbook/$pair'
      preLoaderRoute: typeof ApiPublicCmcOrderbookPairRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedTradesRoute: typeof AuthenticatedTradesRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedTradesRoute: AuthenticatedTradesRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CustodyRoute: CustodyRoute,
  HowItWorksRoute: HowItWorksRoute,
  ManifestoRoute: ManifestoRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  TradeIskTsdRoute: TradeIskTsdRoute,
  TradeLtcTsdRoute: TradeLtcTsdRoute,
  TradeTsdTxcRoute: TradeTsdTxcRoute,
  TradeTsdUsdcRoute: TradeTsdUsdcRoute,
  TradeTxcUsdtRoute: TradeTxcUsdtRoute,
  TradeUsdcTxcRoute: TradeUsdcTxcRoute,
  TradeZcuTsdRoute: TradeZcuTsdRoute,
  ApiPublicCmcAssetsRoute: ApiPublicCmcAssetsRoute,
  ApiPublicCmcSummaryRoute: ApiPublicCmcSummaryRoute,
  ApiPublicCmcTickerRoute: ApiPublicCmcTickerRoute,
  ApiPublicV1AccountRoute: ApiPublicV1AccountRoute,
  ApiPublicV1DepthRoute: ApiPublicV1DepthRoute,
  ApiPublicV1ExchangeInfoRoute: ApiPublicV1ExchangeInfoRoute,
  ApiPublicV1KlinesRoute: ApiPublicV1KlinesRoute,
  ApiPublicV1OpenOrdersRoute: ApiPublicV1OpenOrdersRoute,
  ApiPublicV1PingRoute: ApiPublicV1PingRoute,
  ApiPublicV1TimeRoute: ApiPublicV1TimeRoute,
  ApiPublicV1TradesRoute: ApiPublicV1TradesRoute,
  ApiPublicCmcIndexRoute: ApiPublicCmcIndexRoute,
  ApiPublicV1IndexRoute: ApiPublicV1IndexRoute,
  ApiPublicCmcOrderbookPairRoute: ApiPublicCmcOrderbookPairRoute,
  ApiPublicCmcTradesPairRoute: ApiPublicCmcTradesPairRoute,
  ApiPublicV1Ticker24hrRoute: ApiPublicV1Ticker24hrRoute,
  ApiPublicV1TickerPriceRoute: ApiPublicV1TickerPriceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
